### ISSUE TITLE
`excluded_paths` is Sort of Not Working

### ISSUE THREAD

**Issue by jherdman** [githubocto/repo-visualizer#27]
I'm working on an Elixir + Phoenix project. There are two files I wish to ignore:

- `assets/package-lock.json`
- `priv/repo/structure.sql`

Given this config:

```yaml
name: Create diagram

on:
  workflow_dispatch: {}
  push:
    branches:
      - "AP-47"
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          commit_message: "skip ci"
          excluded_paths: "mix.lock,.github,_build,priv/repo/structure.sql,assets/package-lock.json,nix"
```

I see this:

<img width="981" alt="Screen Shot 2021-08-11 at 1 23 16 PM" src="https://user-images.githubusercontent.com/3300/129074932-f7a70c96-422d-4207-801e-a071404c1e9d.png">

Why is that?
