### ISSUE TITLE
Add option to push to another branch

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [githubocto/repo-visualizer#3]
This is kind of follow up on #2 - since in my repository `master` branch is protected I don't really see any way to use the GH action currently. It could be nice if I could push the diagram to another branch, and then merge it on my own if I want. 

This could be also useful for folks keeping documentation on `docs` branch or for GH Pages hosted on `gh-pages` branch.

**Comment by special-character** [comment]
I ended up making mine run on every push:
```
name: Create diagram
on:
  workflow_dispatch: {}
  push:

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main

```
