### ISSUE TITLE
Please add { dot: true, matchBase: true } to minimatch options

### ISSUE THREAD

**Issue by phil-lgr** [githubocto/repo-visualizer#35]
## Steps to reproduce this issue:

Set `excluded_globs: "**/node_modules/**,**/dist/**,**/lib/**,**/built/**,**/public/**,**/.cache/**"` to exclude nested files in a monorepo

Like this

```yaml
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          commit_message: "chore(core): update diagram"
          output_file: "docs/assets/images/core-repo-diagram.svg"
          excluded_globs: "**/node_modules/*,**/dist/*,**/lib/*,**/built/*,**/public/*,**/.cache/*"
          excluded_paths: "node_modules,dist,lib,built,.cache,public,out,build,.yarn,.vscode,package-lock.json,yarn.lock"
```

## Expected

E.g. files inside /packages/*/.cache are ignored

## Actual behavior

files inside /packages/*/.cache are not ignored by minimatch

---

There is a bunch of bugs with the default minimatch options

Minimatch options:

- https://github.com/micromatch/micromatch#options

Related issues:

- https://github.com/isaacs/minimatch/issues/30#issue-29835003
- https://github.com/micromatch/micromatch/issues/199
