### ISSUE TITLE
Feature: Add option to add diagrams to nested folders

### ISSUE THREAD

**Issue by njm222** [githubocto/repo-visualizer#38]
I really like repo-visualizer! 

But it would be really cool if we could create multiple svgs with an array of objects where the properties of the object are the existing [inputs](https://github.com/githubocto/repo-visualizer#inputs)

...And a bonus feature would be to allow for regex matching so if you want multiple diagrams in the immediate children directories of a particular directory it is easy to do! (instead of copying the 
```
uses: githubocto/repo-visualizer@0.7.1
  with:
    output_file: "images/diagram.svg"
    root_path: "dist,node_modules
```
)

for each svg
